# Generated by Django 4.1 on 2022-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('fecha_nac', models.DateTimeField()),
                ('contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=5)),
                ('promedio', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=100)),
                ('materia_a_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniversidadModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localizacion', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('description', models.TextField(max_length=2000)),
                ('contacto', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
